services:
  - type: web
    name: btc-algorithms-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot.app:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    autoDeploy: true
